export const ERROR = "error",
  SUCCESS = "success",
  INVALID_DATA = "Invalid data",
  USER_NOT_FOUND = "User not found",
  YOU_ALREADY_KNOW_YOU = "You already know you",
  USER_ALREADY_EXISTS = "User already exists",
  UNKNOWN_ERROR = "Something wrong",
  USER_CREATED = "User has been created",
  INCORRECT_USERNAME_OR_PASSWORD = "Wrong username or password.";
